version: '3'
services:
  db:
    image: postgres
    container_name: container_postgres
    restart: unless-stopped
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres



#  myservice:
#    image: docker.pkg.github.com/klochkov777/demo
#    ports:
#      - "8080:8080"
#      - "8443:8443"

  myservice1:
    image: ghcr.io/klochkov777/demo:develop
    ports:
      - "8080:8080"
      - "8443:8443"



  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: password
