name: Docker image

on:
 push:
  branches:
   - develop
  tags:
   - latest

env:
 REGISTRY: ghcr.io
 IMAGE_NAME: Klochkov777/demo

jobs:
 build-and-push-image:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Set up Java
     uses: actions/setup-java@v1.4.4
     with:
      java-version: 20

   - name: Build with Maven and run tests
     run: mvn package

#   - name: Log in to the Container registry
#     uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#     with:
#      registry: ${{ env.REGISTRY }}
#      username: ${{ github.actor }}
#      password: ${{ secrets.GITHUB_TOKEN }}

   - name: Log in to GitHub Container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

   - name: Extract Docker metadata
     id: meta
     uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
     with:
      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


   - name: Build and push Docker image
     uses: docker/build-push-action@v5
     with:
      context: .
      file: ./Dockerfile
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha,mode=max