name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
    tags:
      - latest

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: klochkov777/demo-service1


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

#      - name: Build with Maven
#        run: mvn clean install
#        working-directory: ./demo-service1/
      - name: Change directory to demo-service1
        run: cd ./demo-service1/

      - name: GitHub Packages
        run: | 
          ls ./
          mvn --batch-mode -DuseGitHubPackages=true deploy -f ./pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: GitHub Packages
#        run: mvn --batch-mode -DuseGitHubPackages=true deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          working-directory: ./demo-service1/


      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#      - name: GitHub Packages
#        run: mvn --batch-mode -DuseGitHubPackages=true deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          working-directory: ./demo-service1/

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: demo-service1
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest


#      - name: GitHub Packages
#        run: mvn --batch-mode -DuseGitHubPackages=true deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          working-directory: ./demo-service1/