name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
    tags:
      - latest

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: klochkov777/demo


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
#    defaults: #777
#      run:
#        working-directory: ./demo-service1/ #777

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./demo-service1/



      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: ls place
        run: ls ./

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: demo-service1
#          push: true
#          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        run: docker build -t demo:latest
        working-directory: ./user-service1/

      - name: Push
        run: docker push ghcr.io/klochkov777/demo:latest
#        working-directory: ./user-service1/target/


      - name: GitHub Packages
        run: mvn --batch-mode -DuseGitHubPackages=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#                    context: demo-service1

#          cache-dependency-path: ./demo-service1/
#            path: ./demo-service1

#          file: ./Dockerfile   #777   cache-dependency-path: ./demo-service1   cache: 'path'
