name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

#      - name: Create a Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

      - name: Build with Maven
        run: mvn clean install

      - name: Check target directory
        run: ls ./target



#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check target directory
        run: ls ./target

#      - name: Store artifact in GitHub Packages
#        run: mvn deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store artifact in GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTINGS_PATH: .github/workflows/settings.xml
        run: mvn deploy --settings $SETTINGS_PATH

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dockerhub_username/demo:latest
          context: .

#      - name: Log in to GitHub Container Registry
#        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#      - name: Push Docker Image
#        run: docker push ghcr.io/klochkov777/demo:latest

#      - name: Store artifact in GitHub Packages
#        run: mvn deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}