name: Build and Test

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: #777
      run:
        working-directory: ./demo-service1/ #777

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

#      - name: Build with Maven
#        run: mvn clean install

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run Tests
        run: mvn test